title: My test blog
author: astro-tech
email: test@test.com
description: > # this means to ignore newlines until "baseurl:"
  This test blog site was made during a github tutorial
  called github-pages-with-jekyll.

# social links
twitter_username: your-twitter-handle # DO NOT include the @ character, or else the build will fail!
github_username:  your-github-handle # DO NOT include the @ character, or else the build will fail!

show_excerpts: true # set to false to remove excerpts on the homepage
theme: minima
